version: '3'
services:
    web:
        build: ./web
        environment:
            - APACH_RUN_USER=www-data
            - APACHE_RUN_GROUP=www-data
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        ports:
            - 8080:80
        working_dir: ${APP_PATH_CONTAINER}

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${DB_PATH_HOST}:/var/lib/mysql
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 6080:8080

    composer:
        image: composer:1.6
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        command: composer install